export default details = {
  "track": {
      "album": {
          "album_type": "album",
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "external_urls": {
              "spotify": "https://open.spotify.com/album/4xkM0BwLM9H2IUcbYzpcBI"
          },
          "href": "https://api.spotify.com/v1/albums/4xkM0BwLM9H2IUcbYzpcBI",
          "id": "4xkM0BwLM9H2IUcbYzpcBI",
          "images": [
            
          ],
          "name": "I Love You.",
          "release_date": "2013-04-19",
          "release_date_precision": "day",
          "total_tracks": 11,
          "type": "album",
          "uri": "spotify:album:4xkM0BwLM9H2IUcbYzpcBI"
      },
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
              },
              "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
              "id": "77SW9BnxLY8rJ0RciFqkHh",
              "name": "The Neighbourhood",
              "type": "artist",
              "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "disc_number": 1,
      "duration_ms": 240400,
      "explicit": false,
      "external_ids": {
          "isrc": "USSM11300080"
      },
      "external_urls": {
          "spotify": "https://open.spotify.com/track/2QjOHCTQ1Jl3zawyYOpxh6"
      },
      "href": "https://api.spotify.com/v1/tracks/2QjOHCTQ1Jl3zawyYOpxh6",
      "id": "2QjOHCTQ1Jl3zawyYOpxh6",
      "is_local": false,
      "name": "Sweater Weather",
      "popularity": 92,
      "preview_url": "https://p.scdn.co/mp3-preview/387541e6cab7e39e27acdb2c80ae6274b1182836?cid=ac9e811172564dc0be5cd2ee0fdfd563",
      "track_number": 4,
      "type": "track",
      "uri": "spotify:track:2QjOHCTQ1Jl3zawyYOpxh6"
  },
  "features": [
      {
          "danceability": 0.612,
          "energy": 0.807,
          "key": 10,
          "loudness": -2.81,
          "mode": 1,
          "speechiness": 0.0336,
          "acousticness": 0.0495,
          "instrumentalness": 0.0177,
          "liveness": 0.101,
          "valence": 0.398,
          "tempo": 124.053,
          "type": "audio_features",
          "id": "2QjOHCTQ1Jl3zawyYOpxh6",
          "uri": "spotify:track:2QjOHCTQ1Jl3zawyYOpxh6",
          "track_href": "https://api.spotify.com/v1/tracks/2QjOHCTQ1Jl3zawyYOpxh6",
          "analysis_url": "https://api.spotify.com/v1/audio-analysis/2QjOHCTQ1Jl3zawyYOpxh6",
          "duration_ms": 240400,
          "time_signature": 4
      }
  ],
  "album": [
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 314826,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/6mAuw7R6u4vlNneuBgnC8K"
          },
          "href": "https://api.spotify.com/v1/tracks/6mAuw7R6u4vlNneuBgnC8K",
          "id": "6mAuw7R6u4vlNneuBgnC8K",
          "is_local": false,
          "name": "How",
          "preview_url": "https://p.scdn.co/mp3-preview/3589a34bb22f3851b42ef249488f4b63002fda7a?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:6mAuw7R6u4vlNneuBgnC8K"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 251186,
          "explicit": true,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/7brQHA2CgQpcMBiOlfiXYb"
          },
          "href": "https://api.spotify.com/v1/tracks/7brQHA2CgQpcMBiOlfiXYb",
          "id": "7brQHA2CgQpcMBiOlfiXYb",
          "is_local": false,
          "name": "Afraid",
          "preview_url": "https://p.scdn.co/mp3-preview/c5d97d71aec18c6a3dbc8a7c797963ca2e0f2641?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:7brQHA2CgQpcMBiOlfiXYb"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 238026,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/0yyyapBjZ9Ek1vcpp3e9bj"
          },
          "href": "https://api.spotify.com/v1/tracks/0yyyapBjZ9Ek1vcpp3e9bj",
          "id": "0yyyapBjZ9Ek1vcpp3e9bj",
          "is_local": false,
          "name": "Everybody's Watching Me (Uh Oh)",
          "preview_url": "https://p.scdn.co/mp3-preview/1167ce84661a83ca27a79b80bacd6037d2d43892?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 3,
          "type": "track",
          "uri": "spotify:track:0yyyapBjZ9Ek1vcpp3e9bj"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 240400,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/2QjOHCTQ1Jl3zawyYOpxh6"
          },
          "href": "https://api.spotify.com/v1/tracks/2QjOHCTQ1Jl3zawyYOpxh6",
          "id": "2QjOHCTQ1Jl3zawyYOpxh6",
          "is_local": false,
          "name": "Sweater Weather",
          "preview_url": "https://p.scdn.co/mp3-preview/387541e6cab7e39e27acdb2c80ae6274b1182836?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 4,
          "type": "track",
          "uri": "spotify:track:2QjOHCTQ1Jl3zawyYOpxh6"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 197266,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/6cWpj6c5pNZYEk5KYjNBji"
          },
          "href": "https://api.spotify.com/v1/tracks/6cWpj6c5pNZYEk5KYjNBji",
          "id": "6cWpj6c5pNZYEk5KYjNBji",
          "is_local": false,
          "name": "Let It Go",
          "preview_url": "https://p.scdn.co/mp3-preview/ce78a3294ffebc18eadfc203ab49df6e82dc483d?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 5,
          "type": "track",
          "uri": "spotify:track:6cWpj6c5pNZYEk5KYjNBji"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 267853,
          "explicit": true,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4V37tyDu9CtqYshvrgLke4"
          },
          "href": "https://api.spotify.com/v1/tracks/4V37tyDu9CtqYshvrgLke4",
          "id": "4V37tyDu9CtqYshvrgLke4",
          "is_local": false,
          "name": "Alleyways",
          "preview_url": "https://p.scdn.co/mp3-preview/be01c3000fdf69c621c8773cb57164688a36da55?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 6,
          "type": "track",
          "uri": "spotify:track:4V37tyDu9CtqYshvrgLke4"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 259413,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/3vooOYHU0Fi3ViCG7Ozh0Y"
          },
          "href": "https://api.spotify.com/v1/tracks/3vooOYHU0Fi3ViCG7Ozh0Y",
          "id": "3vooOYHU0Fi3ViCG7Ozh0Y",
          "is_local": false,
          "name": "W.D.Y.W.F.M?",
          "preview_url": "https://p.scdn.co/mp3-preview/7ef2407fe13c69ba755fb385ed57194c0c7df5ff?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 7,
          "type": "track",
          "uri": "spotify:track:3vooOYHU0Fi3ViCG7Ozh0Y"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 246493,
          "explicit": true,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/2Kt1XplPBQBsDKQDa6TssB"
          },
          "href": "https://api.spotify.com/v1/tracks/2Kt1XplPBQBsDKQDa6TssB",
          "id": "2Kt1XplPBQBsDKQDa6TssB",
          "is_local": false,
          "name": "Flawless",
          "preview_url": "https://p.scdn.co/mp3-preview/975ac6445f5afc996b3c67492c9de8b857cbfc23?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 8,
          "type": "track",
          "uri": "spotify:track:2Kt1XplPBQBsDKQDa6TssB"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 209520,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4BDnfINTlfJPmLp1UV6CXt"
          },
          "href": "https://api.spotify.com/v1/tracks/4BDnfINTlfJPmLp1UV6CXt",
          "id": "4BDnfINTlfJPmLp1UV6CXt",
          "is_local": false,
          "name": "Female Robbery",
          "preview_url": "https://p.scdn.co/mp3-preview/50ae9d40521428e7bd008540114c74fb33713048?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 9,
          "type": "track",
          "uri": "spotify:track:4BDnfINTlfJPmLp1UV6CXt"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 268173,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/1NA2NvAgCB4EfcBC8OHfuj"
          },
          "href": "https://api.spotify.com/v1/tracks/1NA2NvAgCB4EfcBC8OHfuj",
          "id": "1NA2NvAgCB4EfcBC8OHfuj",
          "is_local": false,
          "name": "Staying Up",
          "preview_url": "https://p.scdn.co/mp3-preview/8b67612ce8c5bf6f8ac8f96206723d12477a272a?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 10,
          "type": "track",
          "uri": "spotify:track:1NA2NvAgCB4EfcBC8OHfuj"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
                  },
                  "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
                  "id": "77SW9BnxLY8rJ0RciFqkHh",
                  "name": "The Neighbourhood",
                  "type": "artist",
                  "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 261200,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4MUvaBckjtNGlxX1IuHDPW"
          },
          "href": "https://api.spotify.com/v1/tracks/4MUvaBckjtNGlxX1IuHDPW",
          "id": "4MUvaBckjtNGlxX1IuHDPW",
          "is_local": false,
          "name": "Float",
          "preview_url": "https://p.scdn.co/mp3-preview/0b6ca7bbebc60e423cdd514ba67e5b7b8b402ae2?cid=ac9e811172564dc0be5cd2ee0fdfd563",
          "track_number": 11,
          "type": "track",
          "uri": "spotify:track:4MUvaBckjtNGlxX1IuHDPW"
      }
  ],
  "artists": [
      {
          "external_urls": {
              "spotify": "https://open.spotify.com/artist/77SW9BnxLY8rJ0RciFqkHh"
          },
          "followers": {
              "href": null,
              "total": 10080832
          },
          "genres": [
              "modern alternative rock",
              "modern rock",
              "pop",
              "shimmer pop"
          ],
          "href": "https://api.spotify.com/v1/artists/77SW9BnxLY8rJ0RciFqkHh",
          "id": "77SW9BnxLY8rJ0RciFqkHh",
          "images": [
              {
                  "height": 640,
                  "url": "https://i.scdn.co/image/ab6761610000e5ebdf0b5ac84376a0a4b2166816",
                  "width": 640
              },
              {
                  "height": 320,
                  "url": "https://i.scdn.co/image/ab67616100005174df0b5ac84376a0a4b2166816",
                  "width": 320
              },
              {
                  "height": 160,
                  "url": "https://i.scdn.co/image/ab6761610000f178df0b5ac84376a0a4b2166816",
                  "width": 160
              }
          ],
          "name": "The Neighbourhood",
          "popularity": 84,
          "type": "artist",
          "uri": "spotify:artist:77SW9BnxLY8rJ0RciFqkHh"
      }
  ]
}